### ISSUE TITLE
Further vertex attributes

### ISSUE THREAD

**Issue by clhunsen** [se-passau/coronet#92]
To improve over PR #67, we should consider adding further vertex attributes:
- [x] `commit.count.author.and.committer` and `commit.count.author.or.committer` (see [here](https://github.com/se-passau/codeface-extraction-r/pull/67#discussion_r163168892), fixed in PR #127)
- [x] Related to [here](https://github.com/se-passau/codeface-extraction-r/pull/67#discussion_r162909906), we need to improve the `first.activity` attribute by enabling the user to pass several data sources. (fixed in PR #135)
- [x] Related to [here](https://github.com/se-passau/codeface-extraction-r/pull/67#discussion_r162909906), we need to improve the `active.ranges` attribute by incorporating further data sources. Maybe, we should add a parameter `activity.type` as for `add.vertex.attribute.first.activity`.
- [x] Also count committers for `add.vertex.attribute.artifact.editor.count` (see [here](https://github.com/se-passau/codeface-extraction-r/pull/67#discussion_r162936065) and #84, see PR #169)?

- ~~Currently, we only provide vertex attributes for commits, but we definitely should provide functions to add attributes for e-mails and issues. For some further information, see 
[here](https://github.com/se-passau/codeface-extraction-r/pull/67#discussion_r162930063).~~
 (moved into a separate issue, see #170)

**Comment by clhunsen** [comment]
With the merge of PR #169, the last item in this issue is fixed. Closing here. :tada:
